services:
  mysql:
    image: mysql:8.0
    container_name: techchallenge2-mysql
    environment:
      MYSQL_DATABASE: techchallenge2
      MYSQL_USER: fiap
      MYSQL_PASSWORD: fiap123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "fiap", "-pfiap123"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
